#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    bootstrap_after = "myspacevim#after"
    colorscheme = "one"
    colorscheme_bg = "dark"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "colorscheme"

[[layers]]
name = "ctrlp"

[[layers]]
name = "git"

[[layers]]
name = "github"

[[layers]]
name = "lang#javascript"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
name = "SirVer/ultisnips"

[[custom_plugins]]
name = "terryma/vim-multiple-cursors"

[[custom_plugins]]
name = "prettier/vim-prettier"

[[custom_plugins]]
name = "sjl/gundo.vim"

[[custom_plugins]]
name = "hzchirs/vim-material"
name = "kristijanhusak/vim-hybrid-material"
